### ISSUE TITLE
Quiz: Student must not send his answer multiple times

### ISSUE THREAD

**Issue by PhMemmel** [mebis-lp/mod_mootimeter#29]
Currently a student can submit an answer multiple times.

In a quiz scenario this should not be possible. Instead the quiz page should be disabled. Maybe the student even should be redirected to the results page. If there are no results available, there should be a placeholder text informing the student that he has to wait until the teacher shares the results.

**Comment by PM84** [comment]
The student can obviously send his attempt multiple times, and change his decsision, until the teacher stops the question-phase. This will happen with a button in the content-menu 
![image](https://github.com/mebis-lp/mod_mootimeter/assets/7900120/cdfca37e-e5df-455b-9574-d2c47c58a832)
Then it works exactly as you mentioned.

**Comment by PhMemmel** [comment]
Then at least the message should say differently, like "Your answer has been updated.". Also there always should only be one notification banner at the same time

**Comment by PM84** [comment]
Partial fixed, rest won't fix
