### ISSUE TITLE
Quiz: Result page empty chart

### ISSUE THREAD

**Issue by PhMemmel** [mebis-lp/mod_mootimeter#33]
If the teacher has not yet published the results he/her himself/herself cannot view the results which probably is not intended. A teacher would expect to see the results live no matter if he published them to the students or not.

Also: The student will see a chart without any data in it which is confusing. There should be a clear message that the results have not been published yet instead of an empty chart.

**Comment by PM84** [comment]
Fixex with https://github.com/mebis-lp/mod_mootimeter/commit/e271922f7ec0e490970a75cb1ad5d72806e9d636
