### ISSUE TITLE
Icon for delete

### ISSUE THREAD

**Issue by nofonbg** [mebis-lp/mod_mootimeter#34]
<img width="506" alt="trashbin" src="https://github.com/mebis-lp/mod_mootimeter/assets/118652526/20a9a1b4-fd9b-47b9-b9a6-5f39c3811bfb">
I find this switch confusing, you would expect a new random display but not delete, that's what the recycle bin is for?

**Comment by PM84** [comment]
Thank you for the hint, we are discussing it again. Our design agency selected this icon  because it has to represent "reset" and in this case it is ok to use this icon.

**Comment by nofonbg** [comment]
I expected reset-icon to reset the image but not to reset all students inputs since inputs are shown in another dialog.
